on: 
  watch:
    types: [started]
    
name: build trojan-go
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
    - name: Build
      run: make
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.platform }}
        path: build/*
